### ISSUE TITLE
[Bug] Null comparison Exception

### ISSUE THREAD

**Issue by casing** [brung/iosproject#89]
When transitioning to ProfileViewController I occasionally get the following exception.

2015-02-22 00:34:31.778 unnamed[40028:8691009] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot do a comparison query for type: (null)'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001040eef35 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000103d87bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x00000001040eee6d +[NSException raise:format:] + 205
    3   unnamed                             0x0000000100f77d83 PFQueryAssertValidEqualityClauseClass + 345
    4   unnamed                             0x0000000100f77be9 -[PFQuery whereKey:equalTo:] + 74
    5   unnamed                             0x0000000100e26b1b +[ParseClient getUser:surveysComplete:onPage:withCompletion:] + 251
    6   unnamed                             0x0000000100e32204 -[ProfileViewController fetchSurveys] + 260
    7   unnamed                             0x0000000100e31135 -[ProfileViewController viewDidLoad] + 1381
    8   UIKit                               0x0000000102bf4a90 -[UIViewController loadViewIfRequired] + 738
    9   UIKit                               0x0000000102c2306b -[UINavigationController _layoutViewController:] + 44
    10  UIKit                               0x0000000102c235b5 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 216
    11  UIKit                               0x0000000102c236b4 -[UINavigationController _startTransition:fromViewController:toViewController:] + 92
    12  UIKit                               0x0000000102c24487 -[UINavigationController _startDeferredTransitionIfNeeded:] + 523
    13  UIKit                               0x0000000102c24f47 -[UINavigationController __viewWillLayoutSubviews] + 43
    14  UIKit                               0x0000000102d6a509 -[UILayoutContainerView layoutSubviews] + 202
    15  UIKit                               0x0000000102b48973 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 521
    16  QuartzCore                          0x00000001021bfde8 -[CALayer layoutSublayers] + 150
    17  QuartzCore                          0x00000001021b4a0e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
    18  QuartzCore                          0x00000001021b487e _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    19  QuartzCore                          0x000000010212263e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
    20  QuartzCore                          0x000000010212374a _ZN2CA11Transaction6commitEv + 390
    21  UIKit                               0x0000000102acc14d _UIApplicationHandleEventQueue + 2035
    22  CoreFoundation                      0x0000000104024551 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    23  CoreFoundation                      0x000000010401a41d __CFRunLoopDoSources0 + 269
    24  CoreFoundation                      0x0000000104019a54 __CFRunLoopRun + 868
    25  CoreFoundation                      0x0000000104019486 CFRunLoopRunSpecific + 470
    26  GraphicsServices                    0x00000001052819f0 GSEventRunModal + 161
    27  UIKit                               0x0000000102acf420 UIApplicationMain + 1282
    28  unnamed                             0x0000000100e304e3 main + 115
    29  libdyld.dylib                       0x000000010461b145 start + 1
    30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by brung** [comment]
Hoping the checks I put in will prevent this crash.  But def reopen if you see it again after pulling
