### ISSUE TITLE
[Bug] SurveyViewCell cell height issues after creating new Survey

### ISSUE THREAD

**Issue by casing** [brung/iosproject#98]
There are Survey height issues because of the re-use of SurveyViewCell by the TableView.  This is because we are using a Custom UIView within the SurveyViewCell and have to refresh the Custom UIView whenever the table is shown.

**Comment by brung** [comment]
making issue 86 duplicate of this.  I  think overall same issue.

**Comment by brung** [comment]
86 has screenshot https://github.com/brung/iosproject/issues/86

**Comment by casing** [comment]
Going to mark this closed and if a better solution presents itself will have to revisit
